Algoritmo "cap68_teste-para"
// CURSO   : [Linguagem e Lógica de Programação]
// Professor   : Nelio Alves
// Descrição   : Cap. 68 - Teste "Para"
// Autor(a)    : Mariana Molina
// Data atual  : 13/02/2023

// Teste "Para"

Var
// Seção de Declarações das variáveis

   x, y, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  x <- 4
  y <- x + 2
  
  para i de 1 ate x faca
   escreva(x," ",y)
    y<- y + i
  fimpara

Fimalgoritmo