Algoritmo "cap68_teste-para4"
// CURSO   : [Linguagem e Lógica de Programação]
// Professor   : Nelio Alves
// Descrição   : Cap. 68 - Teste "Para"
// Autor(a)    : Mariana Molina
// Data atual  : 13/02/2023

// Teste "Para"

Var
// Seção de Declarações das variáveis

   y, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   y <- 10
   
  para i de 1 ate 4 faca
   escreva(i)
    y <- y + i
     escreval(y)
  fimpara

Fimalgoritmo