Algoritmo "cap68_teste-para2"
// CURSO   : [Linguagem e Lógica de Programação]
// Professor   : Nelio Alves
// Descrição   : Cap. 68 - Teste "Para"
// Autor(a)    : Mariana Molina
// Data atual  : 13/02/2023

// Teste "Para"

Var
// Seção de Declarações das variáveis

   x, y, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

 para i de 1 ate 4 faca

   y <- i - 1
   x <- i * 10
   
   escreva(i)
 
 fimpara

Fimalgoritmo